"use strict";
exports.__esModule = true;
var cat_1 = require("./classes/cat");
var dove_1 = require("./classes/dove");
var duck_1 = require("./classes/duck");
var cat = new cat_1.Cat("Larry");
var dove = new dove_1.Dove("Prince");
var duck = new duck_1.Duck("Donald");
console.log("Cat shit");
cat.getName();
cat.makeSound();
cat.sleep();
console.log("\n");
console.log("Dove shit");
dove.fly();
dove.getName();
dove.makeSound();
dove.sleep();
console.log("\n");
console.log("Duck shit");
duck.fly();
duck.getName();
duck.makeSound();
duck.sleep();
duck.swim();
