/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.malEjemplo.ExportadorCsv;

public class App {
  public static void main(String[] args) {
    ExportadorCsv exportador = new ExportadorCsv();

    System.out.println("Ejemplo malo: ");
    exportador.exportCsv("act.csv");
    exportador.exportPdf("act.pdf");
    exportador.exportXlsx("act.xlsx");

    System.out.println("------------");

    System.out.println("Ejemplo bueno: ");

  }
}
